import type { Locale } from './i18n';
export type GuideSection = { title:string; where:string; steps:string[]; hint:string };
export type CrmGuide = { title:string; intro:string; groups:string[]; sections:GuideSection[]; download:string; back:string; footer:string };
export const crmGuide: Record<Locale, CrmGuide> = {
 nl: { title:'Zo werk je met het CRM', intro:'Begin bij je agenda. Open het klantdossier voor de volgende stap en vink af wanneer het werk klaar is.', groups:['Je dagelijkse werk','Klanten en samenwerking','Documenten en administratie'], download:'Download handleiding als PDF', back:'Terug naar het CRM', footer:'Eén klantdossier, één verantwoordelijke en een duidelijke volgende stap.', sections:[
 { title:'1. Bekijk wat je vandaag moet doen', where:'Agenda', steps:['Open Agenda. Je ziet standaard jouw week. Kies Maand voor een langere periode.','Klik op een datum voor de dagplanning. Bekijk ook Achterstallig en Zonder datum.','Gebruik de medewerkerkeuze om de teamagenda te bekijken.'], hint:'Om 08:00 Madrid-tijd krijgen de aangewezen collega’s met open acties hun persoonlijke e-mailoverzicht. Taken zonder datum staan alleen in het CRM.' },
 { title:'2. Geef een collega een taak', where:'Teamberichten', steps:['Kies Nieuw bericht / taak en selecteer de medewerker.','Schrijf concreet wat er moet gebeuren. Koppel het bericht vanuit een klantdossier als het over een klant gaat.','Laat Maak hier ook een taak van aan en kies een deadline. Verstuur daarna.'], hint:'Een bericht is privé tussen afzender en ontvanger. Een gekoppelde taak is zichtbaar in de teamagenda. De ontvanger krijgt een CRM-melding en een persoonlijke e-mail.' },
 { title:'3. Rond een taak of afspraak af', where:'Agenda', steps:['Vink de taak of afspraak af nadat die is uitgevoerd.','Controleer of er nog een volgende actie nodig is. Plan die met een nieuwe datum.','Een fout vinkje kun je met Heropenen herstellen.'], hint:'Een afgeronde opvolgtaak werkt ook het klantdossier bij. Een toekomstige, afzonderlijk geplande actie blijft bestaan.' },
 { title:'4. Volg een echte klantvraag op', where:'Opvolging', steps:['De werklijst bevat concrete aanvragen, geplande acties en klantreacties. Open de naam.','Bij Volgende stap kies je Bijwerken. Vul verantwoordelijke, actie en datum in.','Gebruik de tabs Overzicht, Mailhistorie & concepten, Afspraken en Historie.'], hint:'Een nieuwe verantwoordelijke krijgt een e-mail. Contacten zonder opvolgbehoefte kun je uit de werklijst halen; hun gegevens blijven bewaard.' },
 { title:'5. Schrijf een passende klantmail', where:'Klantdossier → Mail schrijven', steps:['Eigen mail / AI-concept is de standaard. Schrijf zelf of laat AI onderwerp en tekst maken met dossiercontext.','Controleer ontvanger, inhoud, taal, afgesproken locatie en eventuele bijlagen.','Kies Controleren en versturen. Verstuur pas vanuit het controlevenster.'], hint:'Een concept bewaren verstuurt niets. Alleen bevestigde verzending vinkt de huidige opvolging automatisch af. Flexible Stone-data sheets gaan alleen mee bij een Flexible Stone-mail.' },
 { title:'6. Plan een afspraak op de juiste locatie', where:'Klantdossier → Afspraak plannen', steps:['Leg de met de klant bevestigde datum en tijd vast.','Vul de werkelijke locatie of videolink in. Een afspraak kan ook bij de klant, online of per telefoon zijn.','Bewaar en controleer de afspraak in de agenda.'], hint:'Een afspraak in het CRM zetten verstuurt geen uitnodiging aan de klant. Bevestig de afspraak zelf per mail wanneer dat nodig is.' },
 { title:'7. Vind de klant en zijn gegevens', where:'Contacten / zoeken bovenaan', steps:['Zoek eerst op naam, bedrijf of e-mailadres om dubbele contacten te voorkomen.','Open het contact voor gegevens, offertes en gekoppelde projecten.','Gebruik Opvolging voor de werkafspraken en Aanvragen voor nieuwe binnengekomen verzoeken.'], hint:'Een contact, een aanvraag en een opvolgactie zijn verschillende onderdelen van hetzelfde klantverhaal.' },
 { title:'8. Deel het juiste document', where:'Offertes / Facturen / Prijslijst / Verkooppunten', steps:['Controleer de gegevens en bedragen voordat je downloadt of mailt.','Kies Engels of Spaans bij de download. Klantdocumenten gebruiken de vastgelegde klanttaal.','Gebruik voor verkooppunten het klantdocument. Het tabblad Onze marge is uitsluitend intern.'], hint:'Een PDF downloaden verstuurt geen mail. Kostprijzen en interne bijdragen horen niet in het document voor het verkooppunt.' },
 { title:'9. Houd projecten en administratie bij', where:'Projecten / Inkooporders / Instellingen', steps:['Open het project voor planning, begroting en voortgang. Houd afspraken bij het juiste dossier.','Controleer nieuwe inkoopfacturen voordat je ze goedkeurt. Persoonlijke goedkeurlinks niet doorsturen.','Stel je schermtaal in op Nederlands, Engels of Spaans. Vraag een beheerder om ontbrekende toegang.'], hint:'Een geslaagde melding bevestigt wat is opgeslagen of verstuurd. Bij onzekere mailverzending controleer je eerst de mailbox; verstuur niet opnieuw zonder controle.' },
 ]},
 en: { title:'How to use the CRM', intro:'Start with your calendar. Open the client record for the next step and mark work complete when it is finished.', groups:['Your daily work','Clients and collaboration','Documents and administration'], download:'Download PDF guide', back:'Back to the CRM', footer:'One client record, one person responsible and a clear next step.', sections:[
 { title:'1. See what needs doing today', where:'Calendar', steps:['Open Calendar. Your own week appears by default. Choose Month for a longer period.','Select a date for the daily schedule. Check Overdue and Undated too.','Use the employee selector to view the team calendar.'], hint:'At 08:00 Madrid time, designated colleagues with open actions receive their personal email summary. Undated tasks appear only in the CRM.' },
 { title:'2. Give a colleague a task', where:'Team messages', steps:['Choose New message / task and select the employee.','Describe exactly what needs doing. Start from a client record to link the message to that client.','Keep Also create a task selected and choose a deadline. Then send.'], hint:'The message is private between sender and recipient. A linked task is visible in the team calendar. The recipient receives a CRM notification and a personal email.' },
 { title:'3. Complete a task or appointment', where:'Calendar', steps:['Tick off the task or appointment after doing the work.','Check whether another action is needed. Schedule it with a new date.','Use Reopen to undo an incorrect completion.'], hint:'Completing a follow-up task also updates the client record. A separate action scheduled for the future remains in place.' },
 { title:'4. Follow up a real client request', where:'Follow-up', steps:['The work list contains genuine requests, planned actions and client replies. Open the name.','Under Next step, choose Update. Enter the person responsible, action and date.','Use the Overview, Email history & drafts, Appointments and History tabs.'], hint:'A newly assigned person receives an email. Remove contacts that need no follow-up from the work list; their records are preserved.' },
 { title:'5. Write a suitable client email', where:'Client record → Write an email', steps:['Own email / AI draft is the default. Write your own email or ask AI to create the subject and body using the record.','Check the recipient, wording, language, agreed location and any attachments.','Choose Review and send. Send only from the review window.'], hint:'Saving a draft sends nothing. Only confirmed delivery automatically completes the current follow-up. Flexible Stone data sheets are included only with a Flexible Stone email.' },
 { title:'6. Schedule the right meeting', where:'Client record → Schedule an appointment', steps:['Enter the date and time confirmed with the client.','Enter the actual location or video link. Meetings may be at the client’s premises, online or by phone.','Save and check the appointment in the calendar.'], hint:'Adding an appointment to the CRM does not send the client an invitation. Confirm it yourself by email when needed.' },
 { title:'7. Find a client and their details', where:'Contacts / search at the top', steps:['Search by name, company or email first to avoid duplicate contacts.','Open the contact for details, quotes and linked projects.','Use Follow-up for work agreements and Requests for newly received enquiries.'], hint:'A contact, a request and a follow-up action are separate parts of the same client relationship.' },
 { title:'8. Share the right document', where:'Quotes / Invoices / Price list / Retail partners', steps:['Check details and amounts before downloading or emailing.','Choose English or Spanish for the download. Client documents use the recorded client language.','Use the client document for retail partners. The Our margin tab is internal only.'], hint:'Downloading a PDF sends no email. Cost prices and internal contributions must not appear in the document for the retail partner.' },
 { title:'9. Maintain projects and administration', where:'Projects / Purchase orders / Settings', steps:['Open the project for planning, budget and progress. Keep agreements in the correct record.','Review incoming purchase invoices before approval. Never forward personal approval links.','Set your interface language to Dutch, English or Spanish. Ask an administrator if access is missing.'], hint:'A success message confirms what was saved or sent. If email delivery is uncertain, check the mailbox first; do not send again without checking.' },
 ]},
 es: { title:'Cómo utilizar el CRM', intro:'Empieza por tu agenda. Abre la ficha del cliente para dar el siguiente paso y marca el trabajo como completado cuando termines.', groups:['Tu trabajo diario','Clientes y colaboración','Documentos y administración'], download:'Descargar guía en PDF', back:'Volver al CRM', footer:'Una ficha de cliente, una persona responsable y un siguiente paso claro.', sections:[
 { title:'1. Consulta qué debes hacer hoy', where:'Agenda', steps:['Abre Agenda. Por defecto se muestra tu semana. Elige Mes para ver un periodo más amplio.','Selecciona una fecha para ver el plan del día. Revisa también Atrasadas y Sin fecha.','Utiliza el selector de empleado para consultar la agenda del equipo.'], hint:'A las 08:00, hora de Madrid, los compañeros designados con acciones pendientes reciben su resumen personal por correo. Las tareas sin fecha aparecen solo en el CRM.' },
 { title:'2. Asigna una tarea a un compañero', where:'Mensajes del equipo', steps:['Elige Nuevo mensaje / tarea y selecciona al empleado.','Describe exactamente lo que debe hacerse. Empieza desde la ficha del cliente para vincular el mensaje.','Mantén marcada la opción Crear también una tarea y elige una fecha límite. Después envía.'], hint:'El mensaje es privado entre remitente y destinatario. Una tarea vinculada es visible en la agenda del equipo. El destinatario recibe una notificación en el CRM y un correo personal.' },
 { title:'3. Completa una tarea o cita', where:'Agenda', steps:['Marca la tarea o cita como completada después de realizarla.','Comprueba si hace falta otra acción. Prográmala con una nueva fecha.','Utiliza Reabrir para corregir una tarea marcada por error.'], hint:'Completar una tarea de seguimiento también actualiza la ficha del cliente. Una acción independiente prevista para el futuro se conserva.' },
 { title:'4. Da seguimiento a una solicitud real', where:'Seguimiento', steps:['La lista contiene solicitudes reales, acciones previstas y respuestas de clientes. Abre el nombre.','En Siguiente paso, elige Actualizar. Indica responsable, acción y fecha.','Utiliza las pestañas Resumen, Historial de correos y borradores, Citas e Historial.'], hint:'Un nuevo responsable recibe un correo. Puedes retirar de la lista los contactos que no necesitan seguimiento; sus datos se conservan.' },
 { title:'5. Escribe un correo adecuado', where:'Ficha del cliente → Escribir un correo', steps:['Correo propio / borrador de IA es la opción inicial. Escribe el correo o pide a la IA que prepare asunto y texto con el contexto de la ficha.','Revisa destinatario, texto, idioma, lugar acordado y posibles adjuntos.','Elige Revisar y enviar. Envía únicamente desde la ventana de revisión.'], hint:'Guardar un borrador no envía nada. Solo un envío confirmado completa automáticamente el seguimiento actual. Las fichas técnicas de Flexible Stone se adjuntan únicamente a correos sobre ese producto.' },
 { title:'6. Programa la cita adecuada', where:'Ficha del cliente → Programar una cita', steps:['Introduce la fecha y hora confirmadas con el cliente.','Indica el lugar real o el enlace de videollamada. La cita también puede ser en las instalaciones del cliente, en línea o por teléfono.','Guarda y comprueba la cita en la agenda.'], hint:'Añadir una cita al CRM no envía una invitación al cliente. Confírmala personalmente por correo cuando sea necesario.' },
 { title:'7. Encuentra al cliente y sus datos', where:'Contactos / buscador superior', steps:['Busca primero por nombre, empresa o correo para evitar contactos duplicados.','Abre el contacto para ver datos, presupuestos y proyectos vinculados.','Utiliza Seguimiento para las acciones acordadas y Solicitudes para las nuevas consultas recibidas.'], hint:'El contacto, la solicitud y la acción de seguimiento son partes distintas de la misma relación con el cliente.' },
 { title:'8. Comparte el documento correcto', where:'Presupuestos / Facturas / Lista de precios / Puntos de venta', steps:['Revisa los datos e importes antes de descargar o enviar.','Elige inglés o español para la descarga. Los documentos del cliente utilizan su idioma registrado.','Para los puntos de venta, utiliza el documento del cliente. La pestaña Nuestro margen es solo interna.'], hint:'Descargar un PDF no envía ningún correo. Los costes y las contribuciones internas no deben aparecer en el documento del punto de venta.' },
 { title:'9. Mantén proyectos y administración al día', where:'Proyectos / Pedidos de compra / Ajustes', steps:['Abre el proyecto para consultar planificación, presupuesto y avance. Guarda los acuerdos en la ficha correcta.','Revisa las facturas de compra antes de aprobarlas. No reenvíes enlaces personales de aprobación.','Elige neerlandés, inglés o español como idioma de la interfaz. Solicita acceso a un administrador si te falta.'], hint:'El mensaje de éxito confirma lo guardado o enviado. Si el envío de un correo no está confirmado, consulta primero el buzón; no lo envíes de nuevo sin comprobarlo.' },
 ]},
};
