/** Generated PDF labels; customer-entered descriptions remain unchanged. */
const rows: [string,string,string][] = [
["verkoop − kostprijs", "sales less cost", "venta menos coste"],
["van omzet", "of revenue", "de ingresos"],
["marge", "margin", "margen"],
["Over {n} weken", "In {n} weeks", "Dentro de {n} semanas"],
["Geen gegevens.", "No data.", "Sin datos."],
["n.v.t.", "N/A", "N/D"],
["Alle bedragen zijn exclusief btw.","All amounts exclude VAT.","Todos los importes son sin IVA."],
["Prijslijst & kortingsstaffel","Price list & discount tiers","Lista de precios y descuentos por volumen"],
["{n} producten · {datum} · Marge = winst als percentage van de verkoopprijs. Maximale korting voor break-even.","{n} products · {datum} · Margin = profit as a percentage of selling price. Maximum discount to break even.","{n} productos · {datum} · Margen = beneficio como porcentaje del precio de venta. Descuento máximo para cubrir el coste."],
["Prijs −{pct}%","Price −{pct}%","Precio −{pct}%"],["Winst −{pct}%","Profit −{pct}%","Beneficio −{pct}%"],
["Winst €","Profit €","Beneficio €"],["Marge %","Margin %","Margen %"],["Max. korting %","Max. discount %","Descuento máx. %"],

['Onvoorzien ({pct}%)','Contingency ({pct}%)','Imprevistos ({pct}%)'],
['Onvoorziene werkzaamheden & meerwerk','Unforeseen work and variations','Trabajos imprevistos y adicionales'],
['Begroting per fase','Budget by phase','Presupuesto por fases'],['alle bedragen excl. BTW','all amounts exclude VAT','todos los importes sin IVA'],
['Voortgang van uw project','Your project progress','Avance de su proyecto'],['voor {naam}','for {naam}','para {naam}'],['Totale voortgang','Overall progress','Avance total'],['Fases gereed','Phases completed','Fases terminadas'],['{n} van {totaal}','{n} of {totaal}','{n} de {totaal}'],['Waarde gereed','Value completed','Valor ejecutado'],['van {bedrag} excl. btw','of {bedrag} excluding VAT','de {bedrag} sin IVA'],['In uitvoering','In progress','En ejecución'],['Voortgang per bouwfase','Progress by construction phase','Avance por fase de obra'],['Begroot','Budgeted','Presupuestado'],
['In volgorde van uitvoering. Bedragen volgens de begroting, excl. btw.','In execution order. Amounts follow the budget, excluding VAT.','En orden de ejecución. Importes según el presupuesto, sin IVA.'],['In volgorde van uitvoering. De balk toont hoe ver elke fase is.','In execution order. The bar shows progress in each phase.','En orden de ejecución. La barra muestra el avance de cada fase.'],
['ex. BTW · facturen − credit','excluding VAT · invoices less credit notes','sin IVA · facturas menos abonos'],['ex. BTW · Holded','excluding VAT · Holded','sin IVA · Holded'],['COGS · 12 mnd','cost of goods sold · 12 months','coste de ventas · 12 meses'],['te laat · incl. BTW','overdue · including VAT','vencidas · IVA incluido'],['som van factuurregels · ex. BTW','invoice line totals · excluding VAT','suma de líneas de factura · sin IVA'],['top 12 op winst € · op productregels · 12 mnd','top 12 by profit · product lines · 12 months','12 primeros por beneficio · líneas de producto · 12 meses'],['winst € · op productregels · 12 mnd','profit · product lines · 12 months','beneficio · líneas de producto · 12 meses'],['producten met kostprijs · oplopende marge','products with a recorded cost · margin ascending','productos con coste registrado · margen ascendente'],['Spend','Expenditure','Gasto'],['Financieel overzicht','Financial overview','Resumen financiero'],['Alle bedragen ex. BTW tenzij vermeld · laatste 12 maanden · inkoop uit Holded-grootboek','Amounts exclude VAT unless stated · last 12 months · purchases from the Holded ledger','Importes sin IVA salvo indicación · últimos 12 meses · compras del libro mayor de Holded'],
['in de catalogus','in the catalogue','en el catálogo'],['Lage voorraad','Low stock','Existencias bajas'],['onder de drempel','below the threshold','por debajo del mínimo'],['Te bestellen','To order','Pendiente de pedir'],['actief · ontbreekt op de site','active · missing from the website','activo · falta en la web'],['Collecties','Collections','Colecciones'],['Voorraadwaarde per collectie','Stock value by collection','Valor de existencias por colección'],['alle producten · order-only uitgesloten','all products · order-only excluded','todos los productos · excluye los de pedido especial'],['Hoogste voorraadwaarde','Highest stock value','Mayor valor de existencias'],['top 15 op kostprijs × voorraad','top 15 by cost × stock','15 primeros por coste × existencias'],['Waarde (kostprijs)','Value at cost','Valor al coste'],['Nog geen voorraad.','No stock yet.','Todavía no hay existencias.'],['Lage voorraad — bijbestellen','Low stock - reorder','Existencias bajas - reponer'],['onder de ingestelde drempel · order-only uitgesloten','below the configured minimum · order-only excluded','por debajo del mínimo configurado · excluye los de pedido especial'],['Tekort','Shortfall','Faltante'],['Geen producten onder de voorraaddrempel.','No products below the stock threshold.','No hay productos por debajo del mínimo de existencias.'],['Productoverzicht','Product overview','Resumen de productos'],['Voorraad, waarde en marge · momentopname','Stock, value and margin · current snapshot','Existencias, valor y margen · situación actual'],
['Stelpost','Provisional allowance','Partida provisional'],['stelpost','provisional allowance','partida provisional'],['Onderaanneming','Subcontracting','Subcontratación'],['Materieel','Equipment','Equipos'],['Subtotaal werkzaamheden','Work subtotal','Subtotal de trabajos'],['Totaal (excl. BTW)','Total (excluding VAT)','Total (sin IVA)'],['Aanneemsom (excl. BTW)','Contract sum (excluding VAT)','Importe contratado (sin IVA)'],
['Bij een verbouwing kunnen zich altijd onvoorziene kosten en meerwerk voordoen (verborgen gebreken, hardere ondergrond, gewijzigde keuzes). Werkzaamheden die niet in deze begroting zijn opgenomen vallen erbuiten en worden na overleg apart verrekend.','Renovation may involve unforeseen costs and additional work, such as hidden defects, harder ground or changed choices. Work not included in this budget is excluded and will be charged separately after discussion.','En una reforma pueden surgir costes imprevistos y trabajos adicionales, como defectos ocultos, un terreno más duro o cambios de elección. Los trabajos no incluidos en este presupuesto quedan excluidos y se facturarán por separado tras acordarlos.'],
['Meerwerk wordt uitsluitend uitgevoerd na schriftelijk akkoord van de opdrachtgever en wordt apart verrekend. Een opgenomen onvoorzien-post wordt uitsluitend verrekend voor zover daadwerkelijk gebruikt.','Additional work is carried out only with the client’s written approval and is charged separately. An included contingency allowance is charged only to the extent actually used.','Los trabajos adicionales se realizan únicamente con la aprobación escrita del cliente y se facturan por separado. Una partida de imprevistos incluida se factura únicamente en la medida en que se utilice.'],
['Stelposten zijn richtbedragen: kiest de opdrachtgever een duurdere uitvoering, dan wordt het verschil als meerprijs verrekend; een voordeliger keuze wordt als minderprijs in mindering gebracht.','Provisional allowances are estimates: if the client chooses a more expensive option, the difference is charged; a less expensive choice is deducted.','Las partidas provisionales son estimaciones: si el cliente elige una opción más cara, se cobra la diferencia; si elige una más económica, se descuenta.'],
['Architect en technische leiding vallen buiten deze begroting: de opdrachtgever contracteert hen zelf en voldoet die facturen rechtstreeks.','The architect and technical supervision are excluded from this budget: the client contracts them directly and pays their invoices directly.','El arquitecto y la dirección técnica quedan excluidos de este presupuesto: el cliente los contrata y paga sus facturas directamente.'],
];
export const reportEnglish = Object.fromEntries(rows.map(([key,en])=>[key,en]));
export const reportSpanish = Object.fromEntries(rows.map(([key,,es])=>[key,es]));
