"use client";
import { ActionForm, Field } from '../../../beurs/opvolging/forms';
import { createContract, registerSigned, activatePartner } from './actions';
import type { partnerContracts, partnerProfiles } from '@/lib/db/schema';
const input='w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-neutral-900';
type Contract=typeof partnerContracts.$inferSelect;
export function ContractForm({id,body,previous}:{id:string;body:string;previous:Contract|null}){return <ActionForm action={createContract} label="Nieuwe contractversie bewaren"><input type="hidden" name="contactId" value={id}/><Field label="Overeenkomst en bijlagen"><textarea className={input} name="body" rows={18} defaultValue={body} minLength={100} maxLength={50000} required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Geldig vanaf"><input className={input} name="validFrom" type="date" required defaultValue={previous?.validFrom}/></Field><Field label="Geldig tot"><input className={input} name="validUntil" type="date" required defaultValue={previous?.validUntil}/></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="exclusive" defaultChecked={previous?.exclusive}/>Exclusief gebied afgesproken</label><div className="grid gap-3 sm:grid-cols-3">{[['latitude','Breedtegraad',previous?.latitude],['longitude','Lengtegraad',previous?.longitude],['radiusKm','Straal (km)',previous?.radiusKm]].map(([name,label,value])=><Field key={name} label={label!}><input className={input} name={name!} type="number" step="any" defaultValue={value??''}/></Field>)}</div><Field label="Producten, gebied, minimumafname en uitzonderingen"><textarea className={input} name="territoryTerms" required minLength={5} maxLength={6000} rows={5} defaultValue={previous?.territoryTerms??'Nog overeen te komen; geen exclusiviteit toegezegd.'}/></Field><p className="text-sm text-neutral-500">Neem deze gebiedsafspraken ook letterlijk op in de overeenkomst die beide partijen tekenen.</p><label className="flex gap-2 text-sm"><input type="checkbox" name="legalReviewed"/>Deze volledige versie en bijlagen zijn juridisch gecontroleerd en akkoord bevonden.</label></ActionForm>;}
export function SignedForm({c}:{c:Contract}){return <ActionForm action={registerSigned} label="Ondertekend contract vastleggen"><input type="hidden" name="id" value={c.id}/><input type="hidden" name="contactId" value={c.contactId}/><Field label="PDF met beide handtekeningen (max. 4 MB)"><input className={input} name="file" type="file" accept="application/pdf" required/></Field><Field label="Bevoegde ondertekenaar Habitat One"><input className={input} name="habitatSigner" required minLength={3}/></Field><Field label="Bevoegde ondertekenaar verkooppunt"><input className={input} name="partnerSigner" required minLength={3}/></Field><Field label="Datum beide handtekeningen compleet"><input className={input} name="signedOn" type="date" required/></Field><label className="flex items-start gap-2 text-sm"><input name="confirm" type="checkbox" required/>Ik heb beide handtekeningen, bevoegdheden en alle bijlagen gecontroleerd. Deze PDF komt overeen met deze contractversie en de gebiedsafspraken.</label></ActionForm>;}
export function ActivationForm({id,contracts,p,name}:{id:string;contracts:Contract[];p:typeof partnerProfiles.$inferSelect|null;name:string}){return <ActionForm action={activatePartner} label="Activeren / publicatie bijwerken"><input type="hidden" name="contactId" value={id}/><Field label="Ondertekende overeenkomst"><select className={input} name="contractId" required defaultValue={p?.activeContractId??''}><option value="">Kies een ondertekende versie</option>{contracts.filter(c=>c.signedPath).map(c=><option key={c.id} value={c.id}>Versie {c.version} · {c.validFrom} — {c.validUntil}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2">{[['publicName','Publieke bedrijfsnaam',p?.publicName??name],['publicAddress','Showroomadres',p?.publicAddress],['publicCity','Plaats',p?.publicCity],['publicCountry','Land',p?.publicCountry],['publicEmail','Publiek zakelijk e-mailadres',p?.publicEmail],['publicPhone','Publieke telefoon',p?.publicPhone],['publicWebsite','Website (https://)',p?.publicWebsite],['latitude','Exacte breedtegraad showroom',p?.latitude],['longitude','Exacte lengtegraad showroom',p?.longitude]].map(([n,l,v])=><Field key={n} label={l!}><input className={input} name={n!} defaultValue={v??''} required={!['publicEmail','publicPhone','publicWebsite'].includes(n!)} type={['latitude','longitude'].includes(n!)?'number':'text'} step="any"/></Field>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" name="publish" defaultChecked={p?.published}/>Publiceer deze bedrijfsgegevens op de openbare verkooppuntenkaart</label><label className="flex gap-2 text-sm"><input type="checkbox" name="confirm" required/>De samenwerking is goedgekeurd en deze bedrijfsgegevens mogen openbaar worden getoond.</label></ActionForm>;}
