import { and, desc, eq, inArray, or } from 'drizzle-orm';
import { z } from 'zod';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { requireModuleRead } from '@/lib/auth/guards';
import { db } from '@/lib/db';
import { contacts, partnerContracts, partnerProfiles, documents } from '@/lib/db/schema';
import { PageHeader, Card, CardHeader, CardTitle, CardContent, LinkButton, StatTile } from '@/components/ui';
import { formatEUR } from '@/lib/utils';
import { documentFileUrl } from '@/lib/storage';
import { partnerContractTemplate } from '@/lib/partner-contract';
import { ContractForm, SignedForm, ActivationForm } from './forms';
export const metadata={title:'Verkooppuntovereenkomst'};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const access=await requireModuleRead('producten');const{id}=await params;if(!z.string().uuid().safeParse(id).success)notFound();
 const[c]=await db.select().from(contacts).where(eq(contacts.id,id));if(!c)notFound();const[p]=await db.select().from(partnerProfiles).where(eq(partnerProfiles.contactId,id));
 const contracts=await db.select().from(partnerContracts).where(eq(partnerContracts.contactId,id)).orderBy(desc(partnerContracts.version));
 const purchases=await db.select().from(documents).where(and(or(eq(documents.contactId,id),c.companyId?eq(documents.companyId,c.companyId):undefined),inArray(documents.kind,['invoice','creditnote']))).orderBy(desc(documents.issueDate));
 const counted=purchases.filter(d=>!['draft','void'].includes(d.status));const total=counted.reduce((s,d)=>s+(d.kind==='creditnote'?-Math.abs(Number(d.totalEur)):Number(d.totalEur)),0);
 const downloads=new Map(await Promise.all(contracts.filter(c=>c.signedPath).map(async c=>[c.id,await documentFileUrl(c.signedPath!,300)] as const)));
 return <div className="space-y-6"><PageHeader title={`Samenwerking · ${c.name}`} subtitle="Contracten, exclusiviteit, publicatie en geregistreerde afname." actions={<LinkButton href={`/opvolging/${id}`}>Terug naar dossier</LinkButton>}/><div className="grid gap-3 sm:grid-cols-3"><StatTile label="Partnerstatus" value={p?.active?'Officieel':'Kandidaat'}/><StatTile label="Websitepublicatie" value={p?.published?'Gepubliceerd':'Niet gepubliceerd'}/><StatTile label="Gefactureerd na creditnota’s (incl. btw)" value={formatEUR(total)}/></div><LinkButton href={`/wederverkopers/${id}/presentatie`}>Presentatieafspraak en tegoed beheren</LinkButton>
 <div className="grid items-start gap-6 xl:grid-cols-2"><div className="space-y-6"><Card><CardHeader><CardTitle>Overeenkomst opstellen</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">Het startmodel bevat bespreekpunten, geen kant-en-klaar juridisch advies. Vul commerciële en juridische voorwaarden aan. Iedere opslag maakt een nieuwe versie.</p>{access.heeftCap('schrijven')&&<ContractForm id={id} body={contracts[0]?.body??partnerContractTemplate(c.name)} previous={contracts[0]??null}/>}</CardContent></Card><Card><CardHeader><CardTitle>Afname en facturen</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">Facturen en creditnota’s van dit contact en gekoppelde bedrijf, voor alle producten. Concepten tellen niet mee. Verkoop door de winkel aan eindklanten wordt hier niet verondersteld.</p><div className="space-y-3">{purchases.map(d=><div className="border-b pb-3 text-sm" key={d.id}><Link href={`/invoices/${d.id}`} className="font-medium underline">{d.docNumber??d.title??'Concept'}</Link> · {d.issueDate} · {d.status}<p>{d.kind==='creditnote'?'Creditnota':'Factuur'} {formatEUR(d.totalEur)} · betaald {formatEUR(d.paidEur)}</p>{d.items.map((i,index)=><p key={index} className="text-muted">{i.name} · {i.units} eenheden</p>)}</div>)}{!purchases.length&&<p className="text-sm">Nog geen gekoppelde facturen.</p>}</div></CardContent></Card></div>
 <div className="space-y-6"><Card><CardHeader><CardTitle>Versies & ondertekening</CardTitle></CardHeader><CardContent><div className="space-y-4">{contracts.map(co=><details className="rounded-xl border p-4" key={co.id} open={co===contracts[0]}><summary className="font-medium">Versie {co.version} · {co.signedPath?'Beide handtekeningen vastgelegd':'Concept'}<span className="block text-xs font-normal">{co.validFrom} — {co.validUntil} · {co.exclusive?`${co.radiusKm} km exclusiviteit`:'Geen exclusiviteit'}</span></summary><p className="my-3 whitespace-pre-wrap text-sm">{co.territoryTerms}</p><details><summary className="text-sm underline">Contracttekst bekijken</summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{co.body}</pre></details><a href={`/api/partners/contracts/${co.id}`} className="my-4 block text-sm underline">Contractversie downloaden (tekst)</a>{co.signedPath?<><p className="text-sm">{co.habitatSigner} en {co.partnerSigner} · {co.signedOn}</p>{downloads.get(co.id)&&<a className="text-sm underline" href={downloads.get(co.id)!}>Ondertekende PDF downloaden</a>}<p className="mt-2 break-all text-xs text-muted">SHA-256: {co.signedHash}</p></>:access.heeftCap('schrijven')&&<SignedForm c={co}/>}</details>)}{!contracts.length&&<p className="text-sm">Bewaar eerst een contractversie.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>Officieel activeren</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">Activering vereist een lopend, gecontroleerd en door beide partijen getekend contract. Overlappende exclusieve gebieden worden geblokkeerd. Stopzetten kan in het opvolgdossier.</p>{access.heeftCap('schrijven')&&<ActivationForm id={id} contracts={contracts} p={p??null} name={c.name}/>}</CardContent></Card></div></div></div>;
}
