import { tekst } from '@/lib/i18n/server';
import { and, desc, eq, inArray, or } from 'drizzle-orm';
import { z } from 'zod';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { requireModuleRead } from '@/lib/auth/guards';
import { db } from '@/lib/db';
import { contacts, partnerContracts, partnerProfiles, documents } from '@/lib/db/schema';
import { PageHeader, Card, CardHeader, CardTitle, CardContent, LinkButton, StatTile } from '@/components/ui';
import { formatEUR } from '@/lib/utils';
import { documentFileUrl } from '@/lib/storage';
import { partnerContractDocument, partnerContractTemplate } from '@/lib/partner-contract';
import { ContractForm, SignedForm, ActivationForm } from './forms';
export const metadata={title:'Verkooppuntovereenkomst'};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const t=await tekst();
 const access=await requireModuleRead('producten');const{id}=await params;if(!z.string().uuid().safeParse(id).success)notFound();
 const[c]=await db.select().from(contacts).where(eq(contacts.id,id));if(!c)notFound();const[p]=await db.select().from(partnerProfiles).where(eq(partnerProfiles.contactId,id));
 const contracts=await db.select().from(partnerContracts).where(eq(partnerContracts.contactId,id)).orderBy(desc(partnerContracts.version));
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'});
 const activatable=contracts.filter(c=>c.signedPath&&c.legalReviewed&&c.verifiedAt&&c.validFrom<=today&&c.validUntil>=today);
 const purchases=await db.select().from(documents).where(and(or(eq(documents.contactId,id),c.companyId?eq(documents.companyId,c.companyId):undefined),inArray(documents.kind,['invoice','creditnote']))).orderBy(desc(documents.issueDate));
 const counted=purchases.filter(d=>!['draft','void'].includes(d.status));const total=counted.reduce((s,d)=>s+(d.kind==='creditnote'?-Math.abs(Number(d.totalEur)):Number(d.totalEur)),0);
 const downloads=new Map(await Promise.all(contracts.filter(c=>c.signedPath).map(async c=>[c.id,await documentFileUrl(c.signedPath!,300)] as const)));
 return <div className="space-y-6"><PageHeader title={t("Samenwerking · {naam}",{naam:c.name})} subtitle={t("Contracten, exclusiviteit, publicatie en geregistreerde afname.")} actions={<LinkButton href={`/opvolging/${id}`}>{t("Terug naar dossier")}</LinkButton>}/><div className="grid gap-3 sm:grid-cols-3"><StatTile label={t("Partnerstatus")} value={t(p?.active?'Officieel':'Kandidaat')}/><StatTile label={t("Websitepublicatie")} value={t(p?.published?'Gepubliceerd':'Niet gepubliceerd')}/><StatTile label={t("Gefactureerd na creditnota’s (incl. btw)")} value={formatEUR(total)}/></div><LinkButton href={`/wederverkopers/${id}/presentatie`}>{t("Presentatieafspraak en tegoed beheren")}</LinkButton>
 <div className="grid items-start gap-6 xl:grid-cols-2"><div className="space-y-6"><Card><CardHeader><CardTitle>{t("Overeenkomst opstellen")}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">{t("Vul de afspraken in. Je kunt daarna het complete concept bekijken en opslaan. Ondertekening en activering komen later.")}</p>{access.heeftCap('schrijven')&&<ContractForm id={id} body={contracts[0]?.body??partnerContractTemplate(c.name)} previous={contracts[0]??null} name={c.name} location={{address:[c.addressLine,c.city,c.country].filter(Boolean).join(', '),latitude:c.latitude,longitude:c.longitude}}/>}</CardContent></Card><Card><CardHeader><CardTitle>{t("Afname en facturen")}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">{t("Facturen en creditnota’s van dit contact en gekoppelde bedrijf, voor alle producten. Concepten tellen niet mee. Verkoop door de winkel aan eindklanten wordt hier niet verondersteld.")}</p><div className="space-y-3">{purchases.map(d=><div className="border-b pb-3 text-sm" key={d.id}><Link href={`/invoices/${d.id}`} className="font-medium underline">{d.docNumber??d.title??t("Concept")}</Link> · {d.issueDate} · {d.status}<p>{d.kind==='creditnote'?t("Creditnota"):t("Factuur")} {formatEUR(d.totalEur)} {t("· betaald")} {formatEUR(d.paidEur)}</p>{d.items.map((i,index)=><p key={index} className="text-muted">{i.name} · {i.units} {t("eenheden")}</p>)}</div>)}{!purchases.length&&<p className="text-sm">{t("Nog geen gekoppelde facturen.")}</p>}</div></CardContent></Card></div>
 <div className="space-y-6"><Card><CardHeader><CardTitle>{t("Versies & ondertekening")}</CardTitle></CardHeader><CardContent><div className="space-y-4">{contracts.map(co=><details className="rounded-xl border p-4" key={co.id} open={co===contracts[0]}><summary className="font-medium">{t("Versie")} {co.version} · {co.signedPath?t("Beide handtekeningen vastgelegd"):t("Concept")}<span className="block text-xs font-normal">{co.validFrom} — {co.validUntil} · {co.exclusive?t("{n} km exclusiviteit",{n:co.radiusKm??0}):t("Geen exclusiviteit")}</span></summary><p className="my-3 whitespace-pre-wrap text-sm">{co.territoryTerms}</p><details><summary className="text-sm underline">{t("Contracttekst bekijken")}</summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{partnerContractDocument(co)}</pre></details><a href={`/api/partners/contracts/${co.id}`} className="my-4 block text-sm underline">{t("Contractversie downloaden (tekst)")}</a>{co.signedPath?<><p className="text-sm">{co.habitatSigner} {t("en")} {co.partnerSigner} · {co.signedOn}</p>{downloads.get(co.id)&&<a className="text-sm underline" href={downloads.get(co.id)!}>{t("Ondertekende PDF downloaden")}</a>}<p className="mt-2 break-all text-xs text-muted">SHA-256: {co.signedHash}</p></>:access.heeftCap('schrijven')&&(co.legalReviewed?<SignedForm c={co}/>:<p className="mt-3 text-sm text-muted">{t("Dit is nog een concept. Bewaar na juridische controle een nieuwe gecontroleerde versie; daarna kun je de ondertekende PDF toevoegen.")}</p>)}</details>)}{!contracts.length&&<p className="text-sm">{t("Bewaar eerst een contractversie.")}</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>{t("Officieel activeren")}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">{t("Activering vereist een lopend, gecontroleerd en door beide partijen getekend contract. Overlappende exclusieve gebieden worden geblokkeerd. Stopzetten kan in het opvolgdossier.")}</p>{access.heeftCap('schrijven')&&(activatable.length?<ActivationForm id={id} contracts={activatable} p={p??null} name={c.name}/>:<p className="text-sm">{t("Nog niet beschikbaar. Leg eerst beide handtekeningen vast bij een juridisch gecontroleerd contract dat nu geldig is.")}</p>)}</CardContent></Card></div></div></div>;
}
