import type { KlantTaal } from "@/lib/klant-portal";

/** Compacte vertaaltabel voor het klantportaal (zelfde aanpak als /uren). */
const nl = {
    portaal: "Klantportaal",
    welkom: "Volg de voortgang van uw project en bekijk uw facturen en betalingen.",
    emailLabel: "Uw e-mailadres",
    stuurLink: "Stuur mij een inloglink",
    linkGestuurd: "Als dit e-mailadres bij ons bekend is, staat er binnen een paar minuten een inloglink in uw mailbox. De link is 30 minuten geldig.",
    inloggen: "Inloggen",
    loginKnop: "Log mij in",
    loginUitleg: "Klik op de knop om in te loggen op het klantportaal van Habitat One.",
    linkOngeldig: "Deze inloglink is verlopen of ongeldig. Vraag op de startpagina een nieuwe aan.",
    linkVerlopen: "Deze inloglink is verlopen. Geen probleem — met één klik sturen we een nieuwe naar hetzelfde e-mailadres.",
    stuurNieuweLink: "Stuur mij een nieuwe inloglink",
    mijnProjecten: "Mijn projecten",
    mijnOffertes: "Mijn offertes",
    commissies: "Mijn commissies",
    commissieUitleg: "Voor klanten die u bij ons heeft aangedragen.",
    aangebracht: "Aangebracht",
    opgebouwd: "Opgebouwd",
    uitbetaald: "Uitbetaald",
    geenProjecten: "Er zijn nog geen projecten aan dit e-mailadres gekoppeld. Neem gerust contact met ons op.",
    voortgang: "Voortgang",
    totaalGefactureerd: "Totaal gefactureerd",
    totaalVoorU: "Totaal voor u",
    kostenOverzicht: "Kostenoverzicht",
    arbeid: "Arbeid",
    materialen: "Materialen",
    exclBtw: "excl. btw",
    inclBtw: "incl. btw",
    totaal: "Totaal",
    fase: "Fase",
    klaar: "klaar",
    betalingen: "Facturen & betalingen",
    document: "Document",
    datum: "Datum",
    bedrag: "Bedrag",
    betaald: "Betaald",
    openstaand: "Openstaand",
    status: "Status",
    ontvangenBetalingen: "Ontvangen betalingen",
    voorschotten: "Voorschotten",
    gevraagd: "Gevraagd",
    ontvangen: "Ontvangen",
    meerwerk: "Goedgekeurd meerwerk",
    aanneemsom: "Aanneemsom",
    pdf: "PDF",
    aanmelden: "Aanmelden als klant",
    aanmeldUitleg: "Vul uw gegevens in — daarna ziet u hier automatisch uw project(en) zodra wij ze voor u klaarzetten.",
    mijnGegevens: "Mijn gegevens",
    gegevensUitleg: "Controleer en vul uw gegevens aan — zo staat alles goed op offertes en facturen.",
    naam: "Volledige naam",
    telefoon: "Telefoon",
    mobiel: "Mobiel",
    nifNie: "NIF / NIE / btw-nummer",
    adres: "Adres",
    postcode: "Postcode",
    plaats: "Plaats",
    provincie: "Provincie",
    land: "Land",
    taalVoorkeur: "Taalvoorkeur",
    opslaan: "Opslaan",
    opgeslagen: "Uw gegevens zijn opgeslagen — dank u wel!",
    uitloggen: "Uitloggen",
    disclaimer: "Vragen over uw project? Mail ons op hi@habitat-one.com.",
    statusLabels: { active: "In uitvoering", completed: "Afgerond", on_hold: "Gepauzeerd", planned: "Gepland" } as Record<string, string>,
    docLabels: { estimate: "Offerte", proforma: "Termijnfactuur", invoice: "Factuur", creditnote: "Creditnota" } as Record<string, string>,
  };

/** Alle talen delen de vorm van de NL-tabel, met vrije stringwaarden. */
export type KlantT = { [K in keyof typeof nl]: (typeof nl)[K] extends Record<string, string> ? Record<string, string> : string };

const T: Record<KlantTaal, KlantT> = {
  nl,
  en: {
    portaal: "Client portal",
    welkom: "Follow the progress of your project and view your invoices and payments.",
    emailLabel: "Your email address",
    stuurLink: "Send me a login link",
    linkGestuurd: "If this email address is known to us, a login link will be in your inbox within a few minutes. The link is valid for 30 minutes.",
    inloggen: "Log in",
    loginKnop: "Log me in",
    loginUitleg: "Click the button to log in to the Habitat One client portal.",
    linkOngeldig: "This login link has expired or is invalid. Request a new one on the start page.",
    linkVerlopen: "This login link has expired. No problem — one click sends a fresh one to the same email address.",
    stuurNieuweLink: "Send me a new login link",
    mijnProjecten: "My projects",
    mijnOffertes: "My quotes",
    commissies: "My commissions",
    commissieUitleg: "For clients you referred to us.",
    aangebracht: "Referred",
    opgebouwd: "Accrued",
    uitbetaald: "Paid out",
    geenProjecten: "No projects are linked to this email address yet. Feel free to contact us.",
    voortgang: "Progress",
    totaalGefactureerd: "Total invoiced",
    totaalVoorU: "Total for you",
    kostenOverzicht: "Cost overview",
    arbeid: "Labour",
    materialen: "Materials",
    exclBtw: "excl. VAT",
    inclBtw: "incl. VAT",
    totaal: "Total",
    fase: "Phase",
    klaar: "done",
    betalingen: "Invoices & payments",
    document: "Document",
    datum: "Date",
    bedrag: "Amount",
    betaald: "Paid",
    openstaand: "Outstanding",
    status: "Status",
    ontvangenBetalingen: "Payments received",
    voorschotten: "Advance payments",
    gevraagd: "Requested",
    ontvangen: "Received",
    meerwerk: "Approved extra work",
    aanneemsom: "Contract price",
    pdf: "PDF",
    aanmelden: "Register as a client",
    aanmeldUitleg: "Fill in your details — your project(s) will appear here automatically once we set them up for you.",
    mijnGegevens: "My details",
    gegevensUitleg: "Check and complete your details — so everything is correct on quotes and invoices.",
    naam: "Full name",
    telefoon: "Phone",
    mobiel: "Mobile",
    nifNie: "NIF / NIE / VAT number",
    adres: "Address",
    postcode: "Postal code",
    plaats: "City",
    provincie: "Province",
    land: "Country",
    taalVoorkeur: "Preferred language",
    opslaan: "Save",
    opgeslagen: "Your details have been saved — thank you!",
    uitloggen: "Log out",
    disclaimer: "Questions about your project? Email us at hi@habitat-one.com.",
    statusLabels: { active: "In progress", completed: "Completed", on_hold: "On hold", planned: "Planned" } as Record<string, string>,
    docLabels: { estimate: "Quote", proforma: "Instalment invoice", invoice: "Invoice", creditnote: "Credit note" } as Record<string, string>,
  },
  es: {
    portaal: "Portal del cliente",
    welkom: "Siga el progreso de su proyecto y consulte sus facturas y pagos.",
    emailLabel: "Su correo electrónico",
    stuurLink: "Envíame un enlace de acceso",
    linkGestuurd: "Si conocemos este correo, recibirá un enlace de acceso en unos minutos. El enlace es válido durante 30 minutos.",
    inloggen: "Iniciar sesión",
    loginKnop: "Entrar",
    loginUitleg: "Haga clic en el botón para entrar en el portal del cliente de Habitat One.",
    linkOngeldig: "Este enlace ha caducado o no es válido. Solicite uno nuevo en la página de inicio.",
    linkVerlopen: "Este enlace ha caducado. No pasa nada — con un clic le enviamos uno nuevo al mismo correo.",
    stuurNieuweLink: "Envíame un enlace nuevo",
    mijnProjecten: "Mis proyectos",
    mijnOffertes: "Mis presupuestos",
    commissies: "Mis comisiones",
    commissieUitleg: "Por clientes que nos ha recomendado.",
    aangebracht: "Recomendado",
    opgebouwd: "Acumulado",
    uitbetaald: "Pagado",
    geenProjecten: "Aún no hay proyectos vinculados a este correo. No dude en contactarnos.",
    voortgang: "Progreso",
    totaalGefactureerd: "Total facturado",
    totaalVoorU: "Total para usted",
    kostenOverzicht: "Resumen de costes",
    arbeid: "Mano de obra",
    materialen: "Materiales",
    exclBtw: "IVA excl.",
    inclBtw: "IVA incl.",
    totaal: "Total",
    fase: "Fase",
    klaar: "completado",
    betalingen: "Facturas y pagos",
    document: "Documento",
    datum: "Fecha",
    bedrag: "Importe",
    betaald: "Pagado",
    openstaand: "Pendiente",
    status: "Estado",
    ontvangenBetalingen: "Pagos recibidos",
    voorschotten: "Anticipos",
    gevraagd: "Solicitado",
    ontvangen: "Recibido",
    meerwerk: "Trabajos extra aprobados",
    aanneemsom: "Precio contratado",
    pdf: "PDF",
    aanmelden: "Registrarse como cliente",
    aanmeldUitleg: "Rellene sus datos — sus proyectos aparecerán aquí automáticamente en cuanto los preparemos.",
    mijnGegevens: "Mis datos",
    gegevensUitleg: "Revise y complete sus datos — así todo constará correctamente en presupuestos y facturas.",
    naam: "Nombre completo",
    telefoon: "Teléfono",
    mobiel: "Móvil",
    nifNie: "NIF / NIE / n.º de IVA",
    adres: "Dirección",
    postcode: "Código postal",
    plaats: "Ciudad",
    provincie: "Provincia",
    land: "País",
    taalVoorkeur: "Idioma preferido",
    opslaan: "Guardar",
    opgeslagen: "Sus datos se han guardado — ¡gracias!",
    uitloggen: "Cerrar sesión",
    disclaimer: "¿Preguntas sobre su proyecto? Escríbanos a hi@habitat-one.com.",
    statusLabels: { active: "En ejecución", completed: "Finalizado", on_hold: "En pausa", planned: "Planificado" },
    docLabels: { estimate: "Presupuesto", proforma: "Factura a plazo", invoice: "Factura", creditnote: "Abono" },
  },
};

export function klantT(taal: KlantTaal): KlantT {
  return T[taal];
}
