"use client";
import { useActionState, useState } from 'react';
import { editDraft, saveProfile, syncSent, saveDraft, sendDraft, generateDraft, addMeeting, type Result } from './actions';
import { INTEREST, STAGES } from '@/lib/partners';
import type { partnerProfiles } from '@/lib/db/schema';
const input='w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-neutral-900';
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-sm font-medium">{label}{children}</label>;}
export function ActionForm({action,children,label}:{action:(s:Result,f:FormData)=>Promise<Result>;children?:React.ReactNode;label:string}){
 const [state,form,pending]=useActionState(action,{});return <form action={form} className="space-y-4"><fieldset disabled={pending} className="space-y-4">{children}<button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending?'Bezig…':label}</button></fieldset>{state.error&&<p role="alert" className="text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="text-sm text-green-800">{state.success}</p>}</form>;
}
export function SyncButton(){return <ActionForm action={syncSent} label="Verzonden mails ophalen"/>;}
export function ProfileForm({id,profile,users,interested}:{id:string;profile:typeof partnerProfiles.$inferSelect|null;users:{id:string;name:string|null}[];interested:boolean}){
 return <ActionForm action={saveProfile} label="Dossier opslaan"><input type="hidden" name="contactId" value={id}/><input type="hidden" name="version" value={profile?.version??0}/><div className="grid gap-4 sm:grid-cols-2">
 <Field label="Verkooppuntinteresse"><select className={input} name="interest" defaultValue={profile?.interest??(interested?'interested':'unknown')}>{Object.entries(INTEREST).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
 <Field label="Opvolgfase"><select className={input} name="stage" defaultValue={profile?.stage==='active'?'discussion':profile?.stage??'new'}>{Object.entries(STAGES).filter(([v])=>v!=='active').map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
 <Field label="Verantwoordelijke"><select className={input} name="ownerId" defaultValue={profile?.ownerId??''}><option value="">Nog toewijzen</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field>
 <Field label="Mailtaal"><select className={input} name="language" defaultValue={profile?.language??'en-es'}>{Object.entries({'en-es':'Engels én Spaans',en:'Engels',es:'Spaans',nl:'Nederlands',de:'Duits',fr:'Frans',it:'Italiaans'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
 <Field label="Volgende actie"><input className={input} name="nextAction" maxLength={300} defaultValue={profile?.nextAction??''} placeholder="Bijvoorbeeld showroomvoorstel bespreken"/></Field><Field label="Opvolgen op"><input className={input} name="nextActionOn" type="date" defaultValue={profile?.nextActionOn??''}/></Field></div>
 {profile?.active&&<p className="text-sm">Dit is een officieel verkooppunt. Alleen ‘Gestopt’ trekt de activering en publicatie in.</p>}
 <Field label="Gespreksnotities en afspraken"><textarea className={input} name="notes" rows={5} maxLength={10000} defaultValue={profile?.notes??''}/></Field></ActionForm>;
}
export function Compose({id}:{id:string}){
 const [subject,setSubject]=useState('Flexible Stone — next steps / próximos pasos'),[body,setBody]=useState(''),[instruction,setInstruction]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="space-y-4"><Field label="Aanwijzing voor het AI-concept"><input className={input} value={instruction} onChange={e=>setInstruction(e.target.value)} maxLength={2000} placeholder="Wat wil je deze klant voorstellen?"/></Field><button type="button" disabled={busy} className="rounded-lg border px-4 py-2 text-sm" onClick={async()=>{setBusy(true);setError('');try{const r=await generateDraft(id,instruction);if(r){setSubject(r.subject);setBody(r.body);}else setError('AI niet beschikbaar; schrijf hieronder zelf je mail.');}catch{setError('Concept kon niet worden gemaakt.');}finally{setBusy(false);}}}>{busy?'Concept schrijven…':'Maak concept met dossiercontext'}</button>{error&&<p role="alert">{error}</p>}
 <ActionForm action={saveDraft} label="Concept bewaren"><input type="hidden" name="contactId" value={id}/><Field label="Onderwerp"><input className={input} name="subject" value={subject} onChange={e=>setSubject(e.target.value)} required maxLength={250}/></Field><Field label="Mailtekst"><textarea className={input} name="body" rows={12} value={body} onChange={e=>setBody(e.target.value)} required maxLength={20000}/></Field><p className="text-sm text-neutral-500">De Engelse en Spaanse technische data sheets gaan mee bij verzending. Bewaren verstuurt niets.</p></ActionForm></div>;
}
export function SendForm({id,updatedAt}:{id:string;updatedAt:string}){return <ActionForm action={sendDraft} label="Dit concept versturen"><input type="hidden" name="updatedAt" value={updatedAt}/><input type="hidden" name="id" value={id}/><label className="flex gap-2 text-sm"><input type="checkbox" name="confirm" required/>Ik heb ontvanger, mailtekst en afspraken gecontroleerd.</label></ActionForm>;}
export function MeetingForm({id}:{id:string}){const [date,setDate]=useState('');return <ActionForm action={addMeeting} label="Bevestigde afspraak in agenda zetten"><input type="hidden" name="contactId" value={id}/><input type="hidden" name="startsAt" value={date&&!isNaN(Date.parse(date))?new Date(date).toISOString():''}/><Field label="Afspraak"><input className={input} name="title" required defaultValue="Flexible Stone — samenwerking bespreken"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Datum en tijd (tijdzone van je apparaat)"><input className={input} type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Duur in minuten"><input className={input} name="minutes" type="number" min={5} max={480} defaultValue={30}/></Field></div><Field label="Locatie of videolink"><input className={input} name="location"/></Field><Field label="Notities / bevestiging per mail"><textarea className={input} name="notes" rows={3}/></Field><label className="flex gap-2 text-sm"><input type="checkbox" name="confirmed" required/>Datum en tijd zijn met de klant bevestigd.</label></ActionForm>;}

export function EditDraftForm({id,subject,body,updatedAt}:{id:string;subject:string;body:string;updatedAt:string}){return <details className="mb-4"><summary className="cursor-pointer text-sm underline">Concept bewerken</summary><ActionForm action={editDraft} label="Wijzigingen bewaren"><input type="hidden" name="id" value={id}/><input type="hidden" name="updatedAt" value={updatedAt}/><Field label="Onderwerp concept"><input className={input} name="subject" defaultValue={subject} required maxLength={250}/></Field><Field label="Inhoud concept"><textarea className={input} name="body" rows={10} defaultValue={body} required maxLength={20000}/></Field></ActionForm></details>;}
