import { tekst, datumTaal } from '@/lib/i18n/server';
import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { db } from '@/lib/db';
import { contacts, companies, partnerProfiles, partnerMessages, quoteRequests, emailInbox, sentEmails, users, appointments, activities } from '@/lib/db/schema';
import { requireModuleRead } from '@/lib/auth/guards';
import { mailZichtbaarVoor } from '@/lib/mail-visibility';
import { partnerMailVisible } from '@/lib/partner-context';
import { followupSource, followupSources } from '@/lib/followup-source';
import { confirmedFairDate, FOLLOWUP_MAILS, followupMailKind, hasResellerInterest, recommendedFollowupMail } from '@/lib/followup-mail';
import { PageHeader, Card, CardContent, CardHeader, CardTitle, LinkButton } from '@/components/ui';
import { EditDraftForm, ProfileForm, Compose, SendForm, MeetingForm, ProposalAttachments } from '../forms';
import { FollowupCheck } from '../check';
import { FOLLOWUP_DONE, FOLLOWUP_REOPENED, followupCompleted } from '@/lib/followup-checklist';
import { latestFollowupCompletions } from '@/lib/followup-checklist-data';
import { FollowupLive } from '../live';
export const metadata={title:'Klantdossier'};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const t=await tekst(); const dateLocale=await datumTaal();
 const access=await requireModuleRead('aanvragen');const {id}=await params;if(!z.string().uuid().safeParse(id).success)notFound();
 const [row]=await db.select({c:contacts,p:partnerProfiles,company:companies.name}).from(contacts).leftJoin(partnerProfiles,eq(partnerProfiles.contactId,contacts.id)).leftJoin(companies,eq(companies.id,contacts.companyId)).where(eq(contacts.id,id));if(!row)notFound();
 const {c,p}=row,write=access.heeftCap('schrijven'),canMail=access.magModule('inbox');
 const [team,requests,meetings,history,completionEvents]=await Promise.all([db.select({id:users.id,name:users.name}).from(users),db.select().from(quoteRequests).where(eq(quoteRequests.contactId,id)).orderBy(desc(quoteRequests.createdAt)),db.select().from(appointments).where(eq(appointments.contactId,id)).orderBy(desc(appointments.startsAt)),db.select().from(activities).where(and(eq(activities.contactId,id),inArray(activities.subject,['Verkooppuntdossier bijgewerkt',FOLLOWUP_DONE,FOLLOWUP_REOPENED]))).orderBy(desc(activities.createdAt)).limit(20),latestFollowupCompletions([id])]);
 const outgoing=canMail?await db.select().from(partnerMessages).where(and(eq(partnerMessages.contactId,id),partnerMailVisible(access.email))).orderBy(desc(partnerMessages.createdAt)):[];
 const incoming=canMail&&c.email?await db.select().from(emailInbox).where(and(sql`lower(trim(${emailInbox.fromEmail}))=${c.email.trim().toLowerCase()}`,mailZichtbaarVoor(access.email))).orderBy(desc(emailInbox.receivedAt)).limit(100):[];
 const completion=completionEvents[0],completed=followupCompleted(completion,incoming[0]?.receivedAt??null,p?.nextActionOn,new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'}));
 // Oud CRM-archief alleen via expliciete contactkoppeling; geen privépostvak raden.
 const archived: (typeof sentEmails.$inferSelect)[] = [];
 const origins=followupSources(c.source,requests.map(r=>r.source));
 const resellerInterested=hasResellerInterest(c,p);
 const mailContext={name:c.name,company:row.company??requests.find(r=>r.company)?.company,isFair:origins.some(o=>o.key==='beurs'),meetingDate:confirmedFairDate(c.tags),interests:(c.tags??[]).filter(t=>t.startsWith('wil:')).map(t=>t.slice(4))};
 return <div className="space-y-6"><FollowupLive/><PageHeader title={c.name} subtitle={`${row.company??t(c.type)} · ${c.email??t('Geen e-mailadres')} · ${c.city??t('Plaats onbekend')}`} actions={<LinkButton href="/opvolging">{t("Alle opvolging")}</LinkButton>}/><div className="flex flex-wrap gap-3"><LinkButton href={`/contacts/${id}`}>{t("Contactgegevens")}</LinkButton>{access.magModule('producten')&&<><LinkButton href={`/wederverkopers/${id}/samenwerking`}>{t("Contract, exclusiviteit & afname")}</LinkButton><LinkButton href={`/wederverkopers/${id}/presentatie`}>{t("Presentatiepakket & verrekening")}</LinkButton></>}</div>
 <div className="grid items-start gap-6 xl:grid-cols-[1.1fr_1fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>{t("Relatie en volgende stap")}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">{t("Herkomst:")} {origins.map(o=>t(o.label)).join(' · ')}</p><div className="mb-5 rounded-lg border border-border bg-background/50 px-3 py-2">{write?<FollowupCheck key={`${completion?.id??'new'}:${completed}`} contactId={id} name={c.name} completed={completed} eventId={completion?.id??''}/>:<p className="text-sm">{completed?t("Opvolging afgehandeld"):t("Nog opvolgen")}</p>}<p className="text-xs text-muted">{t("Vink af wanneer de huidige opvolging klaar is. Een nieuwe reactie of volgende opvolgdatum brengt deze klant terug in de werklijst.")}</p></div>{write?<ProfileForm id={id} profile={p} users={team} interested={resellerInterested}/>:<p>{p?.notes||t("Nog geen dossiernotities.")}</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle>{t("Herkomst & aanvragen")}</CardTitle></CardHeader><CardContent><div className="space-y-4">{requests.map(r=><div key={r.id}><p className="text-sm text-muted">{r.createdAt.toLocaleDateString(dateLocale)} · {r.company} · {t(followupSource(r.source).label)}</p><p className="whitespace-pre-wrap text-sm">{r.message}</p></div>)}{!requests.length&&<p className="text-sm text-muted">{t("Nog geen gekoppelde aanvragen. Gespreksnotities kun je hierboven vastleggen.")}</p>}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>{t("Afspraken")}</CardTitle></CardHeader><CardContent><div className="mb-5 space-y-2">{meetings.map(m=><p key={m.id} className="text-sm"><Link href="/agenda" className="underline">{m.title}</Link> · {m.startsAt.toLocaleString(dateLocale,{timeZone:'Europe/Madrid'})} {t("(Madrid) ·")} {m.status}</p>)}</div>{write&&access.magModule('agenda')&&<MeetingForm id={id}/>}</CardContent></Card>
 <details className="rounded-xl border p-4 text-sm"><summary>{t("Wijzigingshistorie (")}{history.length})</summary>{history.map(h=><p key={h.id} className="mt-3">{h.createdAt.toLocaleString(dateLocale)} · {team.find(u=>u.id===h.authorId)?.name??t("Medewerker")} · {t(h.subject??'')}</p>)}</details></div>
 <div className="space-y-6">{canMail&&write&&<Card><CardHeader><CardTitle>{t("Persoonlijke mail voorbereiden")}</CardTitle></CardHeader><CardContent><Compose id={id} context={mailContext} resellerInterested={resellerInterested} initialKind={recommendedFollowupMail(c,p)}/></CardContent></Card>}
 <Card><CardHeader><CardTitle>{t("Mailhistorie & concepten")}</CardTitle></CardHeader><CardContent><div className="space-y-4">{outgoing.map(m=><details key={m.id} open={m.status==='draft'} className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">{m.status==='draft'?t("Concept"):m.status==='sent'?(m.personal?t("Persoonlijk verstuurd"):t("Verzonden mail")):t("Verzending controleren")} · {m.subject}<span className="block text-xs font-normal text-muted">{(m.sentAt??m.createdAt).toLocaleString(dateLocale)} · {m.toEmail} · {m.mailboxUser}</span></summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{m.body}</pre>{followupMailKind(m.source)!=='custom'&&<div className="mb-4 space-y-2"><p className="text-xs text-muted">{t(FOLLOWUP_MAILS[followupMailKind(m.source)])}</p><ProposalAttachments kind={followupMailKind(m.source)}/></div>}{m.attachments.length>0&&<p className="mb-4 text-xs text-muted">{t("Bijlagen:")} {m.attachments.map(a=>a.name).join(', ')}</p>}{m.status==='draft'&&write&&<><EditDraftForm key={m.updatedAt.toISOString()} id={m.id} subject={m.subject} body={m.body} updatedAt={m.updatedAt.toISOString()}/><SendForm id={m.id} updatedAt={m.updatedAt.toISOString()}/></>}</details>)}
 {incoming.map(m=><details key={m.id} className="rounded-xl border border-info/30 bg-info/5 p-4"><summary className="cursor-pointer font-medium">{t("Ontvangen ·")} {m.subject}<span className="block text-xs font-normal">{m.receivedAt?.toLocaleString(dateLocale)}</span></summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{m.bodyText??t("Open de mail om de HTML-inhoud te bekijken.")}</pre><Link className="text-sm underline" href={`/inbox/${m.id}`}>{t("Openen en beantwoorden in dezelfde mailwisseling")}</Link></details>)}
 {archived.length>0&&<details><summary className="text-sm">{t("Eerder CRM-archief (")}{archived.length})</summary>{archived.map(m=><details className="mt-3 rounded-lg border p-3" key={m.id}><summary>{m.subject} · {m.createdAt.toLocaleDateString(dateLocale)}</summary><pre className="whitespace-pre-wrap font-sans text-sm">{m.body}</pre></details>)}</details>}
 {!outgoing.length&&!incoming.length&&!archived.length&&<p className="text-sm text-muted">{t("Nog geen gekoppelde mail. Haal op de opvolglijst eerst Verzonden op.")}</p>}</div></CardContent></Card></div></div></div>;
}
