import { and, desc, eq, sql } from 'drizzle-orm';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { db } from '@/lib/db';
import { contacts, companies, partnerProfiles, partnerMessages, quoteRequests, emailInbox, sentEmails, users, appointments, activities } from '@/lib/db/schema';
import { requireModuleRead } from '@/lib/auth/guards';
import { mailZichtbaarVoor } from '@/lib/mail-visibility';
import { partnerMailVisible } from '@/lib/partner-context';
import { followupSource, followupSources } from '@/lib/followup-source';
import { PageHeader, Card, CardContent, CardHeader, CardTitle, LinkButton } from '@/components/ui';
import { EditDraftForm, ProfileForm, Compose, SendForm, MeetingForm } from '../forms';
export const metadata={title:'Klantdossier'};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const access=await requireModuleRead('aanvragen');const {id}=await params;if(!z.string().uuid().safeParse(id).success)notFound();
 const [row]=await db.select({c:contacts,p:partnerProfiles,company:companies.name}).from(contacts).leftJoin(partnerProfiles,eq(partnerProfiles.contactId,contacts.id)).leftJoin(companies,eq(companies.id,contacts.companyId)).where(eq(contacts.id,id));if(!row)notFound();
 const {c,p}=row,write=access.heeftCap('schrijven'),canMail=access.magModule('inbox');
 const [team,requests,meetings,history]=await Promise.all([db.select({id:users.id,name:users.name}).from(users),db.select().from(quoteRequests).where(eq(quoteRequests.contactId,id)).orderBy(desc(quoteRequests.createdAt)),db.select().from(appointments).where(eq(appointments.contactId,id)).orderBy(desc(appointments.startsAt)),db.select().from(activities).where(and(eq(activities.contactId,id),eq(activities.subject,'Verkooppuntdossier bijgewerkt'))).orderBy(desc(activities.createdAt)).limit(20)]);
 const outgoing=canMail?await db.select().from(partnerMessages).where(and(eq(partnerMessages.contactId,id),partnerMailVisible(access.email))).orderBy(desc(partnerMessages.createdAt)):[];
 const incoming=canMail&&c.email?await db.select().from(emailInbox).where(and(sql`lower(${emailInbox.fromEmail})=${c.email.toLowerCase()}`,mailZichtbaarVoor(access.email))).orderBy(desc(emailInbox.receivedAt)).limit(100):[];
 // Oud CRM-archief alleen via expliciete contactkoppeling; geen privépostvak raden.
 const archived: (typeof sentEmails.$inferSelect)[] = [];
 return <div className="space-y-6"><PageHeader title={c.name} subtitle={`${row.company??c.type} · ${c.email??'Geen e-mailadres'} · ${c.city??'Plaats onbekend'}`} actions={<LinkButton href="/opvolging">Alle opvolging</LinkButton>}/><div className="flex flex-wrap gap-3"><LinkButton href={`/contacts/${id}`}>Contactgegevens</LinkButton>{access.magModule('producten')&&<><LinkButton href={`/wederverkopers/${id}/samenwerking`}>Contract, exclusiviteit & afname</LinkButton><LinkButton href={`/wederverkopers/${id}/presentatie`}>Presentatiepakket & verrekening</LinkButton></>}</div>
 <div className="grid items-start gap-6 xl:grid-cols-[1.1fr_1fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>Relatie en volgende stap</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted">Herkomst: {followupSources(c.source,requests.map(r=>r.source)).map(o=>o.label).join(' · ')}</p>{write?<ProfileForm id={id} profile={p} users={team} interested={!!c.tags?.includes('rol:wederverkoper')}/>:<p>{p?.notes||'Nog geen dossiernotities.'}</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Herkomst & aanvragen</CardTitle></CardHeader><CardContent><div className="space-y-4">{requests.map(r=><div key={r.id}><p className="text-sm text-muted">{r.createdAt.toLocaleDateString('nl-NL')} · {r.company} · {followupSource(r.source).label}</p><p className="whitespace-pre-wrap text-sm">{r.message}</p></div>)}{!requests.length&&<p className="text-sm text-muted">Nog geen gekoppelde aanvragen. Gespreksnotities kun je hierboven vastleggen.</p>}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>Afspraken</CardTitle></CardHeader><CardContent><div className="mb-5 space-y-2">{meetings.map(m=><p key={m.id} className="text-sm"><Link href="/agenda" className="underline">{m.title}</Link> · {m.startsAt.toLocaleString('nl-NL',{timeZone:'Europe/Madrid'})} (Madrid) · {m.status}</p>)}</div>{write&&access.magModule('agenda')&&<MeetingForm id={id}/>}</CardContent></Card>
 <details className="rounded-xl border p-4 text-sm"><summary>Wijzigingshistorie ({history.length})</summary>{history.map(h=><p key={h.id} className="mt-3">{h.createdAt.toLocaleString('nl-NL')} · {team.find(u=>u.id===h.authorId)?.name??'Medewerker'} · {h.subject}</p>)}</details></div>
 <div className="space-y-6">{canMail&&write&&<Card><CardHeader><CardTitle>Persoonlijke mail voorbereiden</CardTitle></CardHeader><CardContent><Compose id={id}/></CardContent></Card>}
 <Card><CardHeader><CardTitle>Mailhistorie & concepten</CardTitle></CardHeader><CardContent><div className="space-y-4">{outgoing.map(m=><details key={m.id} open={m.status==='draft'} className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">{m.status==='draft'?'Concept':m.status==='sent'?(m.personal?'Persoonlijk verstuurd':'Verzonden mail'):'Verzending controleren'} · {m.subject}<span className="block text-xs font-normal text-muted">{(m.sentAt??m.createdAt).toLocaleString('nl-NL')} · {m.toEmail} · {m.mailboxUser}</span></summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{m.body}</pre>{m.attachments.length>0&&<p className="mb-4 text-xs text-muted">Bijlagen: {m.attachments.map(a=>a.name).join(', ')}</p>}{m.status==='draft'&&write&&<><EditDraftForm key={m.updatedAt.toISOString()} id={m.id} subject={m.subject} body={m.body} updatedAt={m.updatedAt.toISOString()}/><SendForm id={m.id} updatedAt={m.updatedAt.toISOString()}/></>}</details>)}
 {incoming.map(m=><details key={m.id} className="rounded-xl border border-info/30 bg-info/5 p-4"><summary className="cursor-pointer font-medium">Ontvangen · {m.subject}<span className="block text-xs font-normal">{m.receivedAt?.toLocaleString('nl-NL')}</span></summary><pre className="my-4 whitespace-pre-wrap font-sans text-sm">{m.bodyText??'Open de mail om de HTML-inhoud te bekijken.'}</pre><Link className="text-sm underline" href={`/inbox/${m.id}`}>Openen en beantwoorden in dezelfde mailwisseling</Link></details>)}
 {archived.length>0&&<details><summary className="text-sm">Eerder CRM-archief ({archived.length})</summary>{archived.map(m=><details className="mt-3 rounded-lg border p-3" key={m.id}><summary>{m.subject} · {m.createdAt.toLocaleDateString('nl-NL')}</summary><pre className="whitespace-pre-wrap font-sans text-sm">{m.body}</pre></details>)}</details>}
 {!outgoing.length&&!incoming.length&&!archived.length&&<p className="text-sm text-muted">Nog geen gekoppelde mail. Haal op de opvolglijst eerst Verzonden op.</p>}</div></CardContent></Card></div></div></div>;
}
